# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty

# Setup
title:            Aditya Rajagopal
tagline:          'Learning to Learn'
description:      'Deep learning, computer vision and robotics enthusiast with the occasional game of DOTA 2'
url:              http://aditya-rajagopal.github.io
baseurl:          /

author:
  name:           'Aditya Rajagopal'
  url:            

paginate:         5

# Custom vars
version:          2.1.0

github:
  #repo:           https://github.com/poole/hyde

#removed relative_permalink : true from line 7 below Permalinks
